cosmos-server/src/main/scala/com/mesosphere/cosmos/UniversePackageCache.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZooKeeperStorage.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/UniversePackageCacheSpec.scala
We ensure that each file in the Zip has all of its parent directories
created before copying it to the filesystem.
Fixes #250.
=> Support repo Zip files without directory entries

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/circe/EncodersDecodersSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/http/MediaTypeSpec.scala
Provides a default implementation of CosmosError.getData which uses
generated Circe Encoders to create a JSON representation of any
instance. Subclasses can still override the default if needed.
Fixes #312.
=> Include all CosmosError subclass arguments in "data" field of response

cosmos-server/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/UniversePackageCache.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala
@jsancio quick fix to the error message we ran into today and spoke about.
```json
{
"message": "Package file [index.json] does not match schema",
"type": "PackageFileSchemaMismatch"
}
```
```json
{
"data": {
"errorMessage": "String: El(DownField(0.3.0),true),El(DownField(versions),true),El(DownArray,true),El(DownField(packages),true)"
},
"message": "Package file [index.json] does not match schema",
"type": "PackageFileSchemaMismatch"
}
```
=> Improve PackageFileSchemaMismatch error to pass along the error that caused it

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageRepositoryIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageSearchSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/repository/PackageRepositorySpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/DefaultRepositories.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZooKeeperStorage.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/MediaTypedDecoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/MediaTypedEncoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/MediaTypedEncoders.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/SelectedPackageSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/UserOptionsSpec.scala
This is the last big "repackaging" change.
=> Move request/response encoders/decoders to the versioned `rpc` packages

project/build.scala, project/plugins.sbt
This PR introduces coursier[1] to the project for dependency resolution rather than the default ivy resolver included with sbt. It is significantly faster at resolving and downloading the dependencies of the project. Below are the runtimes for the project with and without coursier.
With the project already compiled, and an empty cache for ivy (`rm -rf ~/.ivy2/cache`):
```bash
time sbt compile it:compile
<snip>
real    5m13.391s
user    4m35.728s
sys     0m3.244s
```
With the project already compiled, and an empty coursier cache (`rm -rf ~/.coursier/cache`):
```bash
time sbt compile it:compile
<snip>
real    1m27.734s
user    4m51.496s
sys     0m2.680s
```
[1] https://github.com/alexarchambault/coursier
=> Introduce coursier for dependency resolution (attempt 2)

cosmos-json/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/Encoders.scala, cosmos-json/src/main/scala/com/mesosphere/universe/v3/circe/Decoders.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/label/v1/model/PackageMetadata.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v2/model/Installation.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v2/model/ListResponse.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonLabels.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Label.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Response.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ListHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/label/v1/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/label/v1/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/MediaTypedEncoders.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/MarathonLabelsSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/UserOptionsSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/converter/LabelSpec.scala
As a result, the ListHandler response will not contain the new
package fields from the Universe 3.0 schema.
This gets us closer to the CLI integration tests passing (#409). Some things to follow up on:
- @tamarrow this change doesn't fix the CLI test failures because we are now including the `selected` field explicitly in the label even if it wasn't specified in the package. So the CLI tests will need to be updated to expect that field.
- At one point we were running the CLI integration tests against Cosmos regularly. Should we start doing that again? It would have caught the `selected` discrepancy I mentioned above much earlier.
=> Enforce an explicit schema for the "package metadata" Marathon label

cosmos-json/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/Decoders.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v2/model/InstallResponse.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/PackageRenderHandlerSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Response.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageRenderHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/MediaTypedEncoders.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/PackageInstallSpec.scala
Depends on #421 
Fixes #419 
Fixes #410 
Fixes #417 
When reviewing, please only look at the contents of the second commit.
=> Update Install and Render handlers to tolerate v3 packages with optional marathon templates

cosmos-server/src/main/scala/com/mesosphere/cosmos/Flags.scala
Due to localhost not being available for all cloud providers we've been asked to remove DNS names that aren't provided by dc/os itself.
=> Update default value for zookeeperUri to be 127.0.0.1

build/start_ccm_cluster.sh
New environment variable `CCM_AWS_CLUSTER_REGION` can now override the region the cluster is started in.
=> Update start_ccm_cluster.sh to allow aws region to be passed as a parameter

project/build.scala
* Flush out circe exclusion on finch for correct pom creation
* Add `publishTo` and set it to ossrh
* Add `pomExtra` with license, scm urls, and developer list (alphabetical order)
=> Cleanup sbt config in preparation of artifact publishing

cosmos-jsonschema/src/main/scala/com/mesosphere/cosmos/jsonschema/JsonSchema.scala, cosmos-jsonschema/src/test/scala/com/mesosphere/cosmos/jsonschema/JsonSchemaSpec.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/schema/repo, cosmos-render/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala
* Update JsonSchema to take an implicit JsonSchemaFactory rather than JsonValidator
* This allows for more configuration handling on the library side since factories can be cloned and have config added, for example to remap http uris to classpath uris.
* Define JsonSchemaFactory for PackageDefinitionRenderer
* Add v3/schema/repo to resources.
* This resource allows for a resource mapping that is very similar the the 
universe hosted schema `/com/mesosphere/universe/v3/schema/repo` -> `https://universe.mesosphere.com/v3/schema/repo`
=> Update JsonSchema to take JsonSchemaFactory

cosmos-finch/src/main/scala/com/mesosphere/cosmos/finch/FinchExtensions.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageRepositoryIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageSearchSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/PackageRenderHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/RequestErrorsSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/repository/PackageRepositorySpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/rpc/v1/model/ErrorResponseSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/test/CosmosIntegrationTestClient.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/test/CosmosRequest.scala
All public methods on `CosmosIntegrationTestClient` no longer use Finagle `Request`s or `RequestBuilder`s directly; instead, they take instances of a new `CosmosRequest` class and convert them to Finagle `Request`s in a uniform way.
=> Prevent test authors from creating incorrect Finagle Request objects

cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueue.scala
I was getting the following warning:
```
[warn] /home/jose/work/cosmos/cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueue.scala:53: implicit numeric widening
[warn]         stats.stat("nodeCount").add(coordinates.length)
[warn]                                                 ^
[warn] /home/jose/work/cosmos/cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueue.scala:179: implicit numeric widening
[warn]     stats.stat("nodeSize").add(data.length)
[warn]                                     ^
[warn] /home/jose/work/cosmos/cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueue.scala:260: implicit numeric widening
[warn]     stats.stat("nodeSize").add(data.length)
[warn] …
```
=> Fix implicit conversion warning

cosmos-server/src/test/scala/com/mesosphere/cosmos/handler/PackageAddHandlerSpec.scala
When running the unit tests I noticed I would get occasional failures from the `Uri` generator; this should eliminate them.
=> Prevent Gen[Uri] parse errors

cosmos-finch/src/test/scala/com/mesosphere/cosmos/finch/RequestValidatorsSpec.scala, cosmos-finch/src/test/scala/com/mesosphere/cosmos/http/HttpRequest.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageAddSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageRepositoryIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageSearchSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/PackageRenderHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/RequestErrorsSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/http/CosmosRequests.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/repository/PackageRepositorySpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/rpc/v1/model/ErrorResponseSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/test/CosmosIntegrationTestClient.scala
The methods are on a new `CosmosRequests` object. To prevent confusion, I renamed the existing `CosmosRequest` class to `HttpRequest`, which is arguably a more accurate name.
This should simplify writing integration tests!
=> Convenience methods for creating Cosmos endpoint requests

cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/CapabilitiesHandler.scala
with 1.10 release we are going to use new `dcos-log` backend for cluster logs.
That said UI and CLI need a new capability to recognize supported clusters.
Related PRs
DC/OS:
https://github.com/dcos/dcos/pull/832
DC/OS CLI:
https://github.com/dcos/dcos-cli/pull/817
dcos-log project:
https://github.com/dcos/dcos-log
=> add dcos-log capability

cosmos-server/src/it/scala/com/mesosphere/cosmos/ServiceStartSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonPackageRunner.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala
Add a new error called AlreadyStarted to Cosmos so that the CLI will print a better error when a package is already running. The current error has the word 'installed' in it, which does not conform to the new verbs.
=> Add ServiceAlreadyStarted error

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageAddHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/LocalObjectStorage.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/ObjectStorage.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/S3ObjectStorage.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/storage/LocalObjectStorageSpec.scala
This PR will add a method getCreationTime to the ObjectStorage. This will be used for the garbage collection algorithm to determine whether a staging object should be removed or not.
=> Add getCreationTime to ObjectStorage

project/build.scala
These warnings have been around for a while, but in #570 the `-Xfatal-warnings` compiler flag was added, causing our [JAR publishing build](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcosIo_Cosmos_MavenCentral_SnapshotMaster) to fail. While we could try to have the links resolve correctly, that would be [more work](https://issues.scala-lang.org/browse/SI-9311), with not much benefit for now (is anyone using our Scaladoc?).
I've also updated our [CI build](https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcosIo_Cosmos_Ci) to generate documentation, so we can catch problems like this at the PR stage.
=> Disable warnings for unresolved documentation links

README.md, project/build.scala
I'll tag the release commit once this is merged. Then I'll cherry-pick this change to `master`, but set the version to `0.4.0-SNAPSHOT` instead.
=> Set Cosmos version to 0.3.0

cosmos-server/src/it/scala/com/mesosphere/cosmos/ServiceStartSpec.scala
When running the integration tests locally, I've noticed that they would leave a Kafka instance in the cluster after they finished. This would result in some tests failing on the next run. It's been happening for at least a few weeks, and it got annoying enough that I decided to just fix it.
=> Ensure kafka service gets cleaned up after test

build/generate_api.sh, cosmos-server/src/main/resources/com/mesosphere/cosmos/handler/capabilities.raml, cosmos-server/src/main/resources/com/mesosphere/cosmos/handler/package.raml, cosmos-server/src/main/resources/com/mesosphere/cosmos/handler/service.raml, dcos-image/publish-package.bash, docker/ramltools/Dockerfile, docker/ramltools/raml2swagger.js
=> Script for generating API documentation

cosmos-bijection/src/test/scala/com/mesosphere/universe/bijection/PackagingVersionConverterSpec.scala, cosmos-bijection/src/test/scala/com/mesosphere/universe/bijection/UniverseConversionsSpec.scala, cosmos-common/src/test/scala/com/mesosphere/util/PackageUtilSpec.scala, cosmos-json/src/test/scala/com/mesosphere/universe/v3/circe/PackagingVersionEncoderDecoderSpec.scala, cosmos-json/src/test/scala/com/mesosphere/universe/v3/circe/RepositoryEncoderDecoderSpec.scala, cosmos-model/src/test/scala/com/mesosphere/universe/test/TestingPackages.scala, cosmos-model/src/test/scala/com/mesosphere/universe/v3/model/PackagingVersionSpec.scala, cosmos-model/src/test/scala/com/mesosphere/universe/v3/model/PackagingVersionTestCompanion.scala, cosmos-model/src/test/scala/com/mesosphere/universe/v3/model/PackagingVersionTestOps.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/circe/EncodersDecodersSpec.scala
Refactor tests to use Table testing style. With this style we'll be able add new examples (v4 examples) to the tables instead of copying and pasting the tests.
Also moves TestingPackages to cosmos-model, so that all tests in all modules are able to use the example packages.
=> Refactor tests so that it's easy to add v4 packages

cosmos-server/src/it/scala/com/mesosphere/cosmos/finagle/FinagleStreamingSpec.scala, project/build.scala
Mostly straightforward, except that I had to customize how the integration test artifacts are generated by SBT. The defaults in SBT handle artifacts for unit tests, but not integration tests.
=> Publish unit and integration test JARs

cosmos-model/src/main/scala/com/mesosphere/universe/PackageDefinition.scala, cosmos-model/src/main/scala/com/mesosphere/universe/PackagingVersion.scala
DescribeResponse depends on v3 PackageVersion, which means we may need to keep it around. Making it a sealed trait makes this much easier.
=> Make PackagingVersion and PackageDefinition sealed traits

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/PackageRenderHandlerSpec.scala, cosmos-render/src/main/scala/com/mesosphere/cosmos/render/MarathonLabels.scala, cosmos-render/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala
Change the options JSON object that we store in Marathon so that we only
store the user provided options. If the user doesn't provide any option
that is equivalent to the empty JSON objct. E.g. "{}".
The possible values for the DCOS_PACKAGE_OPTIONS are:
1. Missing - the application was deployed with an old
Cosmos so we don't have the user provided options.
2. Empty JSON object - the user didn't provide any options
3. JSON object - contains the user provided options
=> Store only the user provided options

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ServiceDescribeSpec.scala
This tests are misbehaving here and in enterprise. The change to ServiceDescribeSpec makes it so that the package is cleaned up if service/describe fails. The change to PackageInstallIntegrationSpec, makes it so that the failure gives a better error message. The test also waits for any deployments to finish before installing. This failing in Enterprise consistently because of a Conflict.
=> Fix some incorrect tests

cosmos-server/src/main/scala/com/mesosphere/cosmos/HttpProxySupport.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/HttpProxySupportSpec.scala
This ended up being a bigger change than intended. I decided to write property tests for the `no_proxy` parsing to make sure all the edge cases got covered. But to make it easier to write the tests, I first separated the initialization code in `HttpProxySupport` into two parts:
1. parse the values of the system properties (without side effects)
2. set the values in the global system properties
=> Translate host suffixes in no_proxy to JVM syntax

cosmos-common/src/main/scala/com/mesosphere/util/RoundTrip.scala, cosmos-integration-tests/src/it/scala/com/mesosphere/cosmos/NonSharedServiceDescribeSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/HttpErrorResponse.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ItOps.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ItUtil.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageRepositorySpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/Requests.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/RoundTrips.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ServiceDescribeSpec.scala, cosmos-test-common/src/main/scala/com/mesosphere/cosmos/util/RoundTrip.scala, cosmos-test-common/src/test/scala/com/mesosphere/util/RoundTripSpec.scala
I worked on this over the weekend. RoundTrip is an abstraction that takes care of clean up. You can construct it with a pair of functions: one that goes forward (makes a state change) and one that goes backwards (reverts the state change). The value that the RoundTrip stores is the result of the forward function. You can use map and flatMap to create new RoundTrips. You can execute a RoundTrip by either .get()ing the value inside the RoundTrip or .apply()ing a transformation to the value inside it. This is a generalization of the `withSomeStateChange()` methods that are scattered over the code.
=> Add RoundTrip abstraction

cosmos-server/src/main/scala/com/mesosphere/cosmos/HttpProxySupport.scala
This will prevent errors when testing proxies during development.
See http://www.oracle.com/technetwork/java/javase/8u111-relnotes-3124969.html
=> Ensure use of Basic auth for HTTPS tunneling through proxies

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/IntegrationBeforeAndAfterAll.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ItObjects.scala
I have changed the integration tests to fetch the repo json from the new converter service. This makes sure that the converter service is running as expected and helps us test the converter service frequently.
=> Updated integration tests to use the new universe converter service

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ResourceProxyHandler.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/handler/ResourceProxyHandlerSpec.scala
Add content disposition header to make sure the proxied filename is consistent. Addresses [DCOS_OSS-1802](https://jira.mesosphere.com/browse/DCOS_OSS-1802)
=> Add content disposition header in resource proxy endpoint

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/CapabilitiesHandlerSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/CapabilitiesHandler.scala
with DC/OS 1.11 we are introducing new logging API. Also known as dcos-log v2.
A new capability is required to handle the logs properly from dcos-cli.
dcos-log v2 [design doc](https://docs.google.com/document/d/1Z2gWi1H7lc3nNGqLUU9Hecvm9EyPLI-6t3uK1ANlHyA/edit#heading=h.apvnjfls8tkq)
Related PRs:
[dcos-log](https://github.com/dcos/dcos-log/pull/43)
[dcos-cli](https://github.com/dcos/dcos-cli/pull/1105)
[dcos](https://github.com/dcos/dcos/pull/1935)
=> add dcos-log v2 capability

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandler.scala
Address [DCOS-21374](https://jira.mesosphere.com/browse/DCOS-21374)
=> Fix service uninstall when the env var is null in marathon json

docker/ramltools/Dockerfile, project/Deps.scala
Address [DCOS-37674](https://jira.mesosphere.com/browse/DCOS-37674)
We are using a very old version of node js (used for generating docs) which resulted in [this error](https://teamcity.mesosphere.io/viewLog.html?buildId=1079083&buildTypeId=DcosIo_Cosmos_PublishRelease&tab=buildLog&_focus=13619). This is not needed for cosmos 0.5.x and above as we have moved the documentation to dcos docs site.
=> Release patch v0.4.4

cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/HttpClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/PackageCollection.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZkRepositoryList.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/ServiceUninstaller.scala
Address [DCOS-40633](https://jira.mesosphere.com/browse/DCOS-40633)
**Problem** :
When multiple requests (e.g.: Package describe requests) try to use `PackageCollection`, cosmos is translating those multiple requests in to multiple non-synchronized calls to ZK to `createOrSet` and this is problematic as only the first create call succeeds and all the rest of the calls throw an error.
**Solution** :
Move the ZK read logic to be inside the caffeine future `LoadingCache` which auto manages multiple requests that result in futures.
=> Fix a race condition while trying to create zk nodes

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/CustomEndpointHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ServiceDescribeHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ServiceUpdateHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandler.scala
Sidenote : Please cleanup all the branches when you are done.
- Removed the cyclomatic complexity. The code was too complicated to be edited by some one in the future.
- We should think about deprecating the `--all` flag in CLI. If not one is using it, removing it makes sense.
- We should have augmented `EndpointHanlder` to contain a generic routing logic for custom package manager. With this in mind, I have created `CustomEndpointHanlder` to enable us to move the routing logic to `EndpointHanlder` in future. When we had design doc for CustomPackageManager, we had a superficial header/payload based proxying to custom manager. We significantly deviated from this (especially in `UninstallHanlder`) and this PR fixes some of this behavior. 
- Also, by doing the above, it makes is trivial to …
=> Cleanup uninstall handler logic

cosmos-common/src/main/scala/com/mesosphere/cosmos/error/CustomPackageManagerNotFound.scala
It seems we added an extra single quote at the end of the message that should be removed.
```
dcos package install --yes kubernetes-cluster
By Deploying, you agree to the Terms and Conditions https://mesosphere.com/catalog-terms-conditions/#certified-services
Kubernetes on DC/OS.
Documentation: https://docs.mesosphere.com/service-docs/kubernetes-cluster
Issues: https://github.com/mesosphere/dcos-kubernetes-quickstart/issues
Installing Marathon app for package [kubernetes-cluster] version [stub-universe]
the custom manager: '/kubernetes', is not installed for this package'
```
=> cosmos-common: fix typo in the error message

cosmos-common/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/render/PackageDefinitionRendererSpec.scala
Use BigInt instead of int to stop auto-floating point conversion.
=> Use BigInt as number data type

cosmos-common/src/main/scala/com/mesosphere/cosmos/error/UninstallFailed.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/thirdparty/marathon/model/MarathonApp.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/Requests.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ServiceDescribeSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/ServiceUpdateSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/AdminRouter.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/ServiceUninstaller.scala
- More verbose logging to be able to say at which step of uninstall you are or the process failed
- SDK_UNINSTALL env was not being looked at properly
- reduced number of marathon requests (we pulled app two times for unknown reason)
- refactored the overall flow to a pipeline of steps
JIRA issues: DCOS_OSS-4662
=> Add logging to the uninstall function, fix looking for SDK_UNINSTALL env var

cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala
Oh wow, this was truly a ride. First I thought there is a bug in cosmos but then after an hour I found this in marathon API docs (because I could not drop that constraint even from UI).
```
Without specifying this parameter, this method has a patch like semantic:
All values that are not defined in the json, will not change existing values.
This was the default behaviour in previous Marathon versions.
For backward compatibility, we will not change this behaviour, but let users opt in for a proper PUT.
Note: We will change the default behaviour in the next Marathon version to support PATCH and PUT as HTTP methods.
```
JIRA: DCOS-49941
=> Use HTTP PUT as if it was PUT

cosmos-common/src/main/scala/com/mesosphere/universe/v3/model/DcosReleaseVersionParser.scala, cosmos-test-common/src/test/scala/com/mesosphere/universe/v3/model/DcosReleaseVersionParserSpec.scala, cosmos-test-common/src/test/scala/com/mesosphere/universe/v3/model/DcosReleaseVersionSpec.scala
See [DCOS-57014](https://jira.mesosphere.com/browse/DCOS-57014)
Relaxes the stringent regex for DC/OS version to allow for semver complaint pre-release suffix : https://semver.org/#spec-item-9  (Note that we are not strictly semver complaint - like we do not have mandatory major, minor patch nor do we support build metadata to be part of the version string)
=> [DCOS-57014] Change the regex for dc/os version parser to accept any suffix

cosmos-common/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/render/PackageDefinitionRendererSpec.scala
This PR adds the `{{#asJson}}varName{{/asJson}}` function that enables rendering a string as raw, un-escaped JSON.
=> Adding `asJson` template to mustache
