cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MultiRepository.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/UniversePackageCache.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/UniversePackageCacheSpec.scala
Partially address #323 by refactoring the way we fetch universe zip files.
=> Refactor universe client

cosmos-json/src/main/scala/com/mesosphere/universe/v3/circe/Decoders.scala, cosmos-json/src/main/scala/com/mesosphere/universe/v3/circe/Encoders.scala, cosmos-model/src/main/resources/com/mesosphere/universe/v3/repo/meta/schema/v3-repo-schema.json, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/Command.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/PackageDefinition.scala
Correlates to https://github.com/mesosphere/universe/pull/482
=> Update v3 repo schema to use command object instead of pip array directly

cosmos-json/src/main/scala/com/mesosphere/universe/v3/circe/Decoders.scala, cosmos-json/src/main/scala/com/mesosphere/universe/v3/circe/Encoders.scala, cosmos-model/src/main/resources/com/mesosphere/universe/v3/repo/meta/schema/v3-repo-schema.json, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/Architectures.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/Binary.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/Cli.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/HashInfo.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/PackageDefinition.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/Platforms.scala, cosmos-model/src/main/scala/com/mesosphere/universe/v3/model/Resource.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala
WIP for universe changes for specifying binary clis
=> add cli property to universe resource model

cosmos-model/src/main/scala/com/mesosphere/cosmos/model/package.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/model/v1/DescribeResponse.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Common.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Response.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageDescribeHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/http/MediaTypes.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/UserOptionsSpec.scala, project/build.scala
Uses Twitter's Bijection library to define converters between case
classes.
This is a starting point, just looking for early feedback before I get to the other responses that need to be updated.
=> Define package describe response encoder supporting versions v1 and v2

cosmos-json/src/main/scala/com/mesosphere/universe/v2/circe/Decoders.scala, cosmos-json/src/main/scala/com/mesosphere/universe/v3/circe/Decoders.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/repository/UniverseRepositoryFetcherSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/UniversePackageCache.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Response.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/internal/model/CosmosInternalRepository.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/internal/model/PackageDefinition.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/MediaTypedEncoders.scala
I tested this manually by fetching from https://universe.mesosphere.com/repo.
=> Universe v2 to v3 conversion

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageRenderHandler.scala
=> universe v3 equivalent of packageRenderHandler

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageSearchHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/PackageCollection.scala
#370 
We probably want to update the SearchResult to include new info (namely resource.cli) but I'll leave that for another pr.
=> universe v3 equivalent of PackageSearchHandler

cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MultiRepository.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ListVersionsHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/PackageCollection.scala
=> Implement ListVersionsHandler for the Universe v3 model

cosmos-model/src/main/resources/com/mesosphere/universe/v3/repo/meta/schema/v3-repo-schema.json
Update based on https://github.com/mesosphere/universe/pull/491
=> Update v3-repo-schema.json to ensure resource documents set additionalProperties false

cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v2/model/Installation.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v2/model/ListResponse.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Response.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ListHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/http/MediaTypes.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/CosmosRepository.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/MediaTypedEncoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/MediaTypedEncoders.scala
=> universe v3 equivalent of ListHandler

project/build.scala
=> Run specific integration tests with `it:test-only`

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala
=> Fix conversion failure when encoding Marathon package metadata label

cosmos-server/src/main/scala/com/mesosphere/cosmos/MultiRepository.scala
This fixes the failing listVersions test in `PackageDescribeSpec`
=> bugfix for getPackagesByPackageName

cosmos-server/src/it/scala/com/mesosphere/cosmos/repository/PackageRepositorySpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala
=> Fix test failures in PackageRepositorySpec

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala
This fixes the remaining test failures!
=> Update tests to match new default value for `selected` field

cosmos-server/src/it/resources/default-repositories.json, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageSearchSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala
=> Update integration suite to use a v3 universe json

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Response.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/MediaTypedEncoders.scala
=> Update describe to fail when attempting to describe a v3 package with no marathon template

cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v2/model/DescribeResponse.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala
=> Ensure DescribeResponse to not expose releaseVersion

README.md
=> Document the `zookeeperUri` command-line flag in the README

cosmos-json/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Decoders.scala, cosmos-json/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Encoders.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/InstalledPackageInformation.scala, cosmos-model/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/InstalledPackageInformationPackageDetails.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Label.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/converter/Universe.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ListHandler.scala
Fix a regression that was introduced that broke the schema of the v1 response for package list.
=> Fix /package/list so that it actually adheres to the v1 schema

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala
=> Update finch/circe config to exclude null properties from serialized json

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ListHandler.scala
Refactored the code to be more testable and easier to read.
=> List handler refactoring

cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageListIntegrationSpec.scala
=> make test for list handler clean up on failure

cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/DistributedAtomicCounter.scala
=> add DistributedAtomicCounter

cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZkRepositoryList.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/repository/ZkRepositoryListSpec.scala
This is useful for factoring out functionality
=> Rename ZooKeeperStorage to ZkRepositoryList

cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZkRepositoryList.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/repository/ZkRepositoryListSpec.scala
Cherry pick the ZooKeeperStorage rename to ZkRepositoryList to master.
=> Rename ZooKeeperStorage to ZkRepositoryList (#496)

cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/AddResult.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/Operation.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/OperationFailure.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/OperationStatus.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/PendingOperation.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/ProcessorView.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/ProducerView.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/ReaderView.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/circe/EncodersDecodersSpec.scala
The purpose of this PR is to discuss the Install Queue API and whether we want to change some names.
=> Add Install Queue API

cosmos-bijection/src/main/scala/com/mesosphere/universe/bijection/BijectionUtils.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Decoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/http/MediaTypes.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueue.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/OperationStatus.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/PendingOperation.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/installqueue/ProcessorView.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/v1/circe/MediaTypedDecoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/storage/v1/circe/MediaTypedEncoders.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/circe/EncodersDecodersSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueueSpec.scala
This is a follow on to #526. This PR aims to implement the install queue. It satisfies the following interfaces: ProducerView, ProcessorView, and ReaderView. It has tests that depend on ZK, so they have all been ignored. They passed on my machine.
=> Implement install queue

cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala
We need to close the InputStream and disconnect the connection after
every request to universe.
=> Close connections to universe

cosmos-server/src/test/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueueSpec.scala
The problems with Curator turned out to be a red herring, although there is Curator code that I'd say contains a bug. See my comment below for more info.
=> Enable InstallQueueSpec tests with suite-specific ZK test cluster

cosmos-bijection/src/test/scala/com/mesosphere/universe/test/TestingPackages.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/PackageAddSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/ServiceStartSpec.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/http/CosmosRequests.scala, cosmos-server/src/it/scala/com/mesosphere/cosmos/test/InstallQueueFixture.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/handler/PackageAddHandlerSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/test/TestUtil.scala, cosmos-server/src/test/scala/com/mesosphere/universe/TestUtil.scala
This depends on #551. Please review/merge that first!
=> Integration tests for /service/start

project/build.scala
The bigger change is that we are enabling checking for unused imports
=> Update scala compiler flags

cosmos-common/src/main/scala/com/mesosphere/util/PackageUtil.scala, cosmos-common/src/test/scala/com/mesosphere/util/PackageUtilSpec.scala, cosmos-model/src/test/scala/com/mesosphere/Generators.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageAddHandler.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/circe/EncodersDecodersSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/handler/PackageAddHandlerSpec.scala, cosmos-server/src/test/scala/com/mesosphere/cosmos/storage/StagedPackageStorageSpec.scala, cosmos-server/src/test/scala/com/mesosphere/universe/TestUtil.scala, project/build.scala
This finishes the implementation of [DCOS-13635](https://jira.mesosphere.com/browse/DCOS-13635).
=> Utility methods for reading and writing DC/OS packages

NOTICE.markdown, README.md, build.sbt, project/Deps.scala, project/build.scala
Also reword the project description in the README.
=> Include license info in dependency list

project/build.scala, project/plugins.sbt
This covers the first batch of build settings that have been moved to the plugin. I'll have a follow-up PR that takes care of the other settings.
=> Use sbt-dcos build plugin

cosmos-test-common/src/test/scala/com/mesosphere/cosmos/storage/GarbageCollectorSpec.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/storage/installqueue/InstallQueueSpec.scala
This PR changes GarbageCollectorSpec to use the SupportedPackageDefinition generator. It does not alter anything else.
InstallQueueSpec: I wrapped the spec in a definition, parameterized on universeInstall. That way it can be passed the UniverseInstall with a particular package version. Other than the version of package all tests are the same.
=> Finish adding v4 examples to unit tests

cosmos-common/src/main/scala/com/mesosphere/universe/Metadata.scala, cosmos-common/src/main/scala/com/mesosphere/universe/PackageDefinition.scala, cosmos-common/src/main/scala/com/mesosphere/universe/v3/model/VersionSpecification.scala, cosmos-common/src/main/scala/com/mesosphere/universe/v3/syntax/PackageDefinitionOps.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MultiRepository.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/CosmosRepository.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/PackageCollection.scala, cosmos-test-common/src/main/scala/com/mesosphere/Generators.scala, cosmos-test-common/src/main/scala/com/mesosphere/cosmos/finch/TestingMediaTypes.scala, cosmos-test-common/src/main/scala/com/mesosphere/universe/test/TestingPackages.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/repository/LocalPackageCollectionSpec.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/repository/PackageCollectionSpec.scala, cosmos-test-common/src/test/scala/com/mesosphere/universe/v3/model/VersionSpecificationSpec.scala, project/Deps.scala
I ended up going with the generator approach instead of the view approach that we talked about the other day. It does make the generators more complicated; I'll point out where. I decided not to use the view because it seemed too heavyweight a change for a simple feature.
=> Add upgradesTo() method to PackageCollection

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/http/CosmosRequests.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/AdminRouter.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/ServiceClient.scala
I need the service update endpoint in marathon in order to implement service update.
=> Add infrastructure for update

cosmos-common/src/main/scala/com/mesosphere/cosmos/CosmosError.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala
Will be using this errors in cosmos-enterprise for service/update
=> Add Service Update Errors

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ItUtil.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/test/CosmosIntegrationTestClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/AdminRouter.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala
This is necessary to check that deployments have finished.
=> Add list deployments method to admin router

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/repository/PackageRepositorySpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala
The supportedMediaTypes value is used to generate the error messages.
=> Fix supported universe media types errors

cosmos-common/src/main/scala/com/mesosphere/cosmos/error/RepositoryAddIndexOutOfBounds.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageRepositorySpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZkRepositoryList.scala
- Updated error message while adding a repository with an index that would result in out of bound exception
- Added a test case to check the same
=> Update error message while adding a repo with an out of bound index

dcos-image/publish-package.bash
Add the same environment variable to teamcity build
=> Added parameter check to fetch scala version

build.sbt, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/ServiceUninstaller.scala
- Removed full stack trace where an exception is expected.
- Removed duplication of dependency specification.
=> Suppress stack trace

cosmos-common/src/main/scala/com/mesosphere/cosmos/error/TimeoutError.scala, cosmos-common/src/main/scala/com/mesosphere/universe/common/circe/Encoders.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/ZkRepositoryList.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/zookeeper/Clients.scala
- Promise is used only in `ZkRepositoryList`
- A constant field is created in zookeeper class for the duration of wait.
- Helper method throws or returns the completed promise.
=> Always complete the promise

cosmos-common/src/main/scala/com/mesosphere/cosmos/error/AmbiguousAppId.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/error/FailedToStartUninstall.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/error/MarathonAppDeleteError.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/error/MarathonAppNotFound.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/error/UninstallNonExistentAppForPackage.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Decoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/circe/Encoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/ServiceDescribeRequest.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/Decoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v2/circe/Encoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/thirdparty/marathon/circe/Decoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/thirdparty/marathon/circe/Encoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/thirdparty/marathon/model/AppId.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/render/PackageDefinitionRendererSpec.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/thirdparty/marathon/circe/EncodersDecodersSpec.scala
Did this while working on something else, figured I should make a separate PR for it to prevent diff noise.
=> Moved Encoder and Decoder for AppId to companion object

dcos-image/publish-package.bash, docs/cosmos.raml
Need to generate this file https://github.com/dcos/dcos-docs/blob/master/1.10/api/package-manager.yaml
=> Add full cosmos documentation

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/ServiceUninstaller.scala
Partially addresses [DCOS-17237](https://jira.mesosphere.com/browse/DCOS-17237).
Apologies for the delay on this, I thought I might not be able to have a test case for it but I eventually found a scenario that reproduced the issue consistently.
=> Stop uninstall background task if Marathon app vanishes

docs/cosmos.raml, docs/endpoints/package-describe.raml, docs/endpoints/package-list-versions.raml, docs/endpoints/package-resource.raml, docs/package.raml
- Add package-resource.raml in endpoints.
- Remove package-add.raml
=> Update documentaion for new endpoints (1.11)

cosmos-common/src/main/scala/com/mesosphere/universe/PackageDefinition.scala
Supporting https://github.com/mesosphere/package-registry/pull/16/
=> Add an advanced rewrite method for resources in Package Definition

cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonClient.scala
Address [DCOS-19500](https://jira.mesosphere.com/browse/DCOS-19500)
=> Always force update the marathon app

cosmos-common/src/main/scala/com/mesosphere/cosmos/circe/Encoders.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/jsonschema/JsonSchema.scala
Address [DCOS_OSS-2223](https://jira.mesosphere.com/browse/DCOS_OSS-2223)
=> Fix bug where comsos initializes empty objects for optional json elements from json schema

cosmos-common/src/main/scala/com/mesosphere/cosmos/finch/EndpointHandler.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-server/src/main/resources/logback.xml, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/render/PackageDefinitionRendererSpec.scala
Partially Address [DCOS-38727](https://jira.mesosphere.com/browse/DCOS-38727)
Refer [this doc](https://docs.google.com/document/d/1MnjR3YwCGuCyWGZ8XlhGBgHgFvRwngUQK3hfI0SbcHE/edit) for comments on testing. After releasing this to DC/OS, we can merge https://github.com/mesosphere/dcos-commons/pull/2610
=> Improve Options rendering for mustache templating engine

cosmos-common/src/main/scala/com/mesosphere/cosmos/finch/EndpointHandler.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/ResourceProxyHandlerIntegrationSpec.scala, cosmos-server/src/main/resources/logback.xml, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/HttpClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonPackageRunner.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/ServiceClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Services.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ResourceProxyHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/package.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala, project/Deps.scala
Address [DCOS_OSS-3690](https://jira.mesosphere.com/browse/DCOS_OSS-3690)
TODO : Updated to latest scala version. Need to do the same in ee version as well.
=> Improve logging formatting and upgrade scala version

cosmos-common/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/MediaTypes.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/InstallRequest.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/ServiceDescribeRequest.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/ServiceUpdateRequest.scala, cosmos-common/src/main/scala/com/mesosphere/cosmos/rpc/v1/model/UninstallRequest.scala, cosmos-common/src/main/scala/com/mesosphere/universe/MediaTypes.scala, cosmos-common/src/main/scala/com/mesosphere/universe/PackageDefinition.scala, cosmos-common/src/main/scala/com/mesosphere/universe/PackagingVersion.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/IntegrationBeforeAndAfterAll.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ItObjects.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageDescribeSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/PackageInstallIntegrationSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/Requests.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/ServiceDescribeSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/ServiceUpdateSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandlerSpec.scala, cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/test/CosmosIntegrationTestClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/AdminRouter.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/AdminRouterClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Cosmos.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/MarathonPackageRunner.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/Services.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ServiceDescribeHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ServiceUpdateHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/CustomPackageManagerRouter.scala, cosmos-test-common/src/main/scala/com/mesosphere/cosmos/http/TestContext.scala, scalastyle-config.xml
Partially address comments in https://github.com/dcos/cosmos/pull/739
=> Fix several code formatting errors

cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/CustomEndpointHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ServiceDescribeHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/ServiceUpdateHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/UninstallHandler.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/CustomPackageManagerRouter.scala
uninstall will not proceed if the package manager is not installed
as a note: tested this from cluster UI and cli to double check errors, cluster UI hangs with no error when cosmos reject uninstall request.
=> [DCOS-42020] Check for package manager before doing any uninstall work

project/Deps.scala
releasing 0.6.1 for containing custom package managers, bumping master to 0.6.2-SNAPSHOT
=> Bump to 0.6.2-snapshot 

cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala
Currently, cosmos [does not mention any charset encoding](https://github.com/dcos/cosmos/blob/36ac6f02ae5ffe0ce000efe4955a2ed44d459c7b/cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/UniverseClient.scala), and thus it is defaulting to whatever the system property `file.encoding` provides. This is `US-ASCII` in centos, `UTF-8` in macOS etc.. To have a predictable/consistent behavior, we should explicitly specify the charset. 
https://github.com/mesosphere/universe/pull/2022 ensures older versions of cosmos continue to work without any changes.
We should use `UTF-8` as charset. Definitions like [this one](https://github.com/mesosphere/dcos-commons/blob/24d8077c23ab8d1b9e691cdf44886e1b1035afaf/frameworks/kafka/universe/config.json#L956) where `\u2019` is part of string text …
=> Add charset to Default UniverseClient

build.sbt, cosmos-common/src/main/scala/com/mesosphere/cosmos/render/PackageDefinitionRenderer.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/HttpClient.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/package.scala
Address [DCOS-46937](https://jira.mesosphere.com/browse/DCOS-46937)
=> Add retries for resource and repositories upstreams

cosmos-common/src/main/scala/com/mesosphere/cosmos/thirdparty/marathon/model/MarathonApp.scala
Partially revert the change made in https://github.com/dcos/cosmos/pull/764
Ref https://github.com/mesosphere/marathon/blob/43cee2540108b67f4cf63946271c90e09bea563e/docs/docs/rest-api/public/api/v2/types/environmentVariable.raml
=> Read marathon env as Map[String, Json]

cosmos-integration-tests/src/main/scala/com/mesosphere/cosmos/handler/PackageInstallIntegrationSpec.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/service/CustomPackageManagerRouter.scala
Jira [DCOS-44111](https://jira.mesosphere.com/browse/DCOS-44111)
=> Handle uninstall gracefully for packages with no custom managers

cosmos-common/src/main/scala/com/mesosphere/cosmos/error/EndpointUriConnection.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/HttpClient.scala
JIRA issues: DCOS-54077
Co-authored-by: Tarun Gupta Akirala <takirala@users.noreply.github.com>
=> Ignore exceptions when closing stream

cosmos-common/src/main/scala/com/mesosphere/universe/Metadata.scala, cosmos-common/src/main/scala/com/mesosphere/universe/PackageDefinition.scala, cosmos-common/src/main/scala/com/mesosphere/universe/bijection/UniverseConversions.scala, cosmos-common/src/main/scala/com/mesosphere/universe/v3/model/ReleaseVersion.scala, cosmos-server/src/main/scala/com/mesosphere/cosmos/repository/PackageCollection.scala, cosmos-test-common/src/main/scala/com/mesosphere/universe/bijection/TestUniverseConversions.scala, cosmos-test-common/src/main/scala/com/mesosphere/universe/test/TestingPackages.scala, cosmos-test-common/src/test/resources/com/mesosphere/universe/v3/circe/expected-encoded-repo.json, cosmos-test-common/src/test/scala/com/mesosphere/cosmos/finch/RequestValidatorsSpec.scala, project/Deps.scala, project/build.properties
Universe schema PR mesosphere/universe#2387
Jira : [DCOS-58438](https://jira.mesosphere.com/browse/DCOS-58438)
=> Add new fields for knownIssues and lastUpdated date

dcos-image/publish-package.bash
Update  --acl bucket-owner-full-control for aws s3 cp since we are using STS aws credentials now.
=> Update --acl bucket-owner-full-control
